server:
  port: 8010
eureka:
  instance:
    hostname: localhost
    status-page-url: http://${eureka.instance.hostname}:${server.port} #eureka服务器页面中status的请求路径
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #eureka注册中心服务器地址
spring:
  application:
    name: microservice-simple-consumer-movie