server:
  port: 8010
user:
  userServiceUrl: http://localhost:8010/
eureka:
  client:
    serviceUrl: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: microservice-simple-consumer-movie